import logging
import urllib2
import json
from urlparse import urlparse

logger = logging.getLogger(__name__)


class TransmissionException(Exception):
    """Used for exceptions generated by TransmissionClient object"""
    pass


class TransmissionClient(object):
    """Object to communicate with Transmission RPC interface"""
    def __init__(self, url):
        self.url = url
        self.session_id = ""
        self.rpc_version_minimum = 1
        parsed_url = urlparse(self.url)
        self.logger = logger.getChild(parsed_url.netloc)

    def get_session(self):
        """Get session information from Transmission"""
        return self._request("session-get")

    def get_download_dir(self):
        """Get the download dir relative to root on the server running transmission"""
        return self.get_session()["download-dir"]

    def check_connection(self):
        """Ensure that remote transmission version is suitable for us"""
        session_info = self.get_session()
        if session_info["rpc-version-minimum"] != self.rpc_version_minimum:
            raise TransmissionException("This version of RPC not supported")

    def add_torrent(self, url, download_dir=None):
        """
        Add a torrent to remote transmission.
        This will succeed if there is a duplicate already on the remote machine.
        :param download_dir: If set specify a download_dir to use for torrent
        """
        arguments = {"filename": url}
        if download_dir is not None:
            arguments["download-dir"] = download_dir
        try:
            return self._request("torrent-add", arguments)
        except TransmissionException as exception:
            if "duplicate torrent" in exception.response_data["result"]:
                self.logger.warn("Already added torrent '%s'" % (url,))
                return exception.response_data["arguments"]
            else:
                raise exception

    def _request(self, method, arguments=None):
        """
        Run a generic RPC call on remote transmission
        """
        self.logger.debug("Perfoming request %s" % (method,))
        request_dict = {"method": method}
        if arguments is not None:
            request_dict["arguments"] = arguments

        request_data = json.dumps(request_dict)
        self.logger.debug("Request data: %s" % (request_data,))
        request = urllib2.Request(self.url, request_data)
        request.add_header("Content-Type", "json; charset=UTF-8")
        request.add_header("X-Transmission-Session-Id", self.session_id)

        try:
            response = urllib2.urlopen(request)
        except urllib2.HTTPError as http_error:
            if http_error.code == 409:
                logger.debug("Updating session ids")
                self.session_id = http_error.info()["X-Transmission-Session-Id"]
                return self._request(method, arguments)
            else:
                raise http_error
        except urllib2.URLError as url_error:
            logger.error("Found URL error when trying to connect to '%s'" % (self.url,))
            raise url_error

        return self._decode_response(response)

    def _decode_response(self, response):
        """
        Decode resposne as returned from _request
        """
        response_content = response.read()
        try:
            response_data = json.loads(response_content)
        except ValueError as exception:
            self.logger.error("Failed to decode response")
            response.read()
            self.logger.error("\n@@@\n" + response_content + "\n@@@\n")
            raise exception

        self.logger.debug("Response: %s" % (response_data,))
        if response_data["result"] != "success":
            exception = TransmissionException("RPC failure: %s" % (response_data["result"],))
            exception.response_data = response_data
            raise exception
        return response_data["arguments"]
